import React from 'react';
import { RiToolsFill, RiBookFill, RiComputerLine } from 'react-icons/ri';
import Card from './components/Card'; // Importing the Card component

const LandingPage = () => {
  return (
    <>
      <div className='flex flex-col justify-center items-center gap-4'>
        <div className='flex flex-col justify-center items-center pt-16 gap-4'> {/* Reduced top margin from pt-16 to pt-8 */}
          <div className='text-5xl font-semibold text-center'>Pick Parts. Build Your PC. <br/>Compare and Share.</div>
          <div className='text-xl font-medium text-gray-700 py-2'>We provide part selection, pricing, and compatibility guidance for do-it-yourself computer builders.</div>
          <button className='bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded flex items-center mt-2'> {/* Reduced top margin from mt-4 to mt-2 */}
            <RiToolsFill className='mr-2' /> Start Your Build
          </button>

          {/* Cards under the second button */}
          <div className='flex flex-col justify-center items-center mt-2 gap-2 text-center'> 
            <div className='text-5xl font-semibold'>Build Guides</div>
            <div className='text-xl text-gray-700 py-2'>Building your own PC and need ideas on where to get started? Explore our build guides which cover systems for a variety of use-cases and budgets.</div>
            <button className='bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded flex items-center mt-2'> {/* Reduced top margin from mt-4 to mt-2 */}
             <RiBookFill className='mr-2' />  View Build Guides
            </button>
            <div className="mt-2 w-full grid grid-cols-3 gap-2"> 
                {/* First Card */}
                <Card
                  imageUrl="src/assets/images/sample.jpeg"
                  title="Title 1"
                  subheading="Subheading 1"
                  helperText="Helper text 1"
                  price="$ 1000"
                />
                {/* Second Card */}
                <Card
                  imageUrl="src/assets/images/sample.jpeg"
                  title="Title 2"
                  subheading="Subheading 2"
                  helperText="Helper text 2"
                  price="$ Price"
                />
                {/* Third Card */}
                <Card
                  imageUrl="src/assets/images/sample.jpeg"
                  title="Title 3"
                  subheading="Subheading 3"
                  helperText="Helper text 3"
                  price="$ Price"
                />
              </div>
          </div>

          {/* Cards under the third button */}
          <div className='flex flex-col justify-center items-center gap-2 mt-2 text-center'>
            <div className='text-5xl font-semibold'>Completed Builds</div>
            <div className='text-xl text-gray-700 py-2'>Browse thousands of PC builds generated by users showing their partlist, photos and overall build experience.</div>
            <button className='bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded flex items-center mt-2'> 
              <RiComputerLine className='mr-2' /> View Completed Builds
            </button>
            <div className=" w-full grid grid-cols-3 gap-2 mt-2"> {/* Reduced top margin from mt-4 to mt-2 */}
                {/* Fourth Card */}
                <Card
                  imageUrl="src/assets/images/sample.jpeg"
                  title="Title 1"
                  subheading="Subheading 1"
                  helperText="Helper text 1"
                  price="$ Price"
                  isMostPopular={true}
                />
                
                {/* Fifth Card */}
                <Card
                  imageUrl="src/assets/images/sample.jpeg"
                  title="Title 2"
                  subheading="Subheading 2"
                  helperText="Helper text 2"
                  price="$ Price"
                />
                {/* Sixth Card */}
                <Card
                  imageUrl="src/assets/images/sample.jpeg"
                  title="Title 3"
                  subheading="Subheading 3"
                  helperText="Helper text 3"
                  price="$ Price"
                />
                {/* Seventh Card */}
                <Card
                  imageUrl="src/assets/images/sample.jpeg"
                  title="Title 4"
                  subheading="Subheading 4"
                  helperText="Helper text 4"
                  price="$ Price"
                />
                {/* Eighth Card */}
                <Card
                  imageUrl="src/assets/images/sample.jpeg"
                  title="Title 5"
                  subheading="Subheading 5"
                  helperText="Helper text 5"
                  price="$ Price"
                />
                {/* Ninth Card */}
                <Card
                  imageUrl="src/assets/images/sample.jpeg"
                  title="Title 6"
                  subheading="Subheading 6"
                  helperText="Helper text 6"
                  price="$ Price"
                />
              </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default LandingPage;
